// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZ9CqzUvYYhIynrW8fgfMzkB0nFAkYqY',
    appId: '1:784997307458:web:f9affc45eab5a5596f49db',
    messagingSenderId: '784997307458',
    projectId: 'waslet-kheir',
    authDomain: 'waslet-kheir.firebaseapp.com',
    storageBucket: 'waslet-kheir.firebasestorage.app',
    measurementId: 'G-KBY16MG19P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXd-a2HE_SeGrbNMUgIz2Pcj1g43X3h2s',
    appId: '1:784997307458:android:579df3cd1f8d79956f49db',
    messagingSenderId: '784997307458',
    projectId: 'waslet-kheir',
    storageBucket: 'waslet-kheir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChIycVn2x7XO-ZpKSpzkJBd5zkUex2rKs',
    appId: '1:784997307458:ios:6c08ba7b75bd069e6f49db',
    messagingSenderId: '784997307458',
    projectId: 'waslet-kheir',
    storageBucket: 'waslet-kheir.firebasestorage.app',
    iosBundleId: 'com.example.wasletKhier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChIycVn2x7XO-ZpKSpzkJBd5zkUex2rKs',
    appId: '1:784997307458:ios:6c08ba7b75bd069e6f49db',
    messagingSenderId: '784997307458',
    projectId: 'waslet-kheir',
    storageBucket: 'waslet-kheir.firebasestorage.app',
    iosBundleId: 'com.example.wasletKhier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXZ9CqzUvYYhIynrW8fgfMzkB0nFAkYqY',
    appId: '1:784997307458:web:a9b5c4df2b3bc17e6f49db',
    messagingSenderId: '784997307458',
    projectId: 'waslet-kheir',
    authDomain: 'waslet-kheir.firebaseapp.com',
    storageBucket: 'waslet-kheir.firebasestorage.app',
    measurementId: 'G-5FQ2Y49SMD',
  );
}
